### ISSUE TITLE
Is sorting output file supported?

### ISSUE THREAD

**Issue by kobynet** [polagoab/merge-properties-maven-plugin#8]
Since merging multiple files, it usually more convenient to seek for property when final file is sorted.

Is there a way to sort final file through the plugin?

**Comment by perlan** [comment]
I'm sorry but sorting is currently not possible since the plugin uses a standard java.util.Properties class for merging all properties and as far as I know, the Properties class have no support for sorting the property keys. To support sorting  (and also #4) , the plugin needs to implements it's own serializer for java properties files. Pull request are always welcome.

**Comment by perlan** [comment]
Due to PR #9 and the switch to commons-configuration2, sorting was now an easy fix.
